name: NodeJS with Grunt

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Use the latest version of Node.js, plus the 3 most recent LTS lines
        node-version:
          - latest
          - lts/*
          - lts/-1
          - lts/-2 # Probably EOL depending on release schedules, but still good to test

    steps:
    - uses: actions/checkout@v7

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        grunt
